name: Hello World
on: push
jobs:
  hello-world-job:
    runs-on: ububtu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "$(cat hello-world.txt)"